---
title: "STA5075: Ch6 Notes"
author: "Jessica Stow (STWJES003@myuct.ac.za)"
date: "2025-02-05"
output: 
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Loops
nsim <- 10000 # number of simulations
emax <- numeric(nsim) # empty vector to store values generated in for loop

for(i in 1:nsim) {
  vals <- rexp(10, rate = 1/5) # generates 10 random draws from the exponential distribution
  emax[i] <- max(vals) # get the max of these values, sotring each iteration of the loop
  }

hist(emax, 
     main = "", 
     xlab = "max of 10 Exp(5) values")
```

```{r}
# Functions
# create a function to calculate the mean of a vector
calcMean <- function(my_vector, decimals = 3){
  n <- length(my_vector) 
  my_mean <- sum(my_vector)/n 
  round_mean <- round(my_mean, digits = decimals)
  return(round_mean)
}

# Create a vector of 5 arbitrary numbers
x <- c(3.215, 0.561, 0.714, 1.643, 1.227)

# use the function
calcMean(my_vector = x, decimals = 1)

mean(x) == calcMean(my_vector = x)
```